In [157]:
import sklearn as sk
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
import codecs, json 
from sklearn.manifold import LocallyLinearEmbedding
from sklearn.decomposition import PCA
from sklearn.decomposition import IncrementalPCA
from sklearn.decomposition import KernelPCA
from sklearn.decomposition import SparsePCA
from sklearn.manifold import MDS
from sklearn.manifold import Isomap
from sklearn.manifold import TSNE
from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import GaussianRandomProjection
from sklearn.decomposition import FastICA
from sklearn.decomposition import MiniBatchDictionaryLearning
from sklearn.random_projection import SparseRandomProjection
import keras
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.optimizers import Adam

## Sampled randomly 2000 rows out of the test data

In [158]:
df = pd.read_csv("/content/drive/MyDrive/VD4/fashion-mnist_test.csv")
X = df.iloc[:, 1:]
y = df.iloc[:, :1]

X = X.sample(frac=0.2)
y = y.loc[X.index, :]

In [159]:
y

label
1153      3
3665      3
7872      8
7275      9
4944      1
...     ...
6693      1
3502      5
4345      4
5896      1
3141      2

[2000 rows x 1 columns]

In [160]:
label_dictionnary = {0:'T-shirt/top', 1:'Trouser', 2:'Pullover', 
                     3:'Dress', 4:'Coat', 5:'Sandal', 6:'Shirt', 
                     7:'Sneaker', 8:'Bag', 9:'Ankle boot' }
def true_label(x):
    return label_dictionnary[x]

## PCA

In [161]:
pca = PCA(n_components=2)
X_r = pca.fit(X).transform(X)


In [162]:
X

pixel1  pixel2  pixel3  pixel4  ...  pixel781  pixel782  pixel783  pixel784
1153       0       0       0       0  ...         0         0         0         0
3665       0       0       0       0  ...         0         0         0         0
7872       0       0       0       0  ...         6         8         0         0
7275       0       0       0       0  ...         0         0         0         0
4944       0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
6693       0       0       0       0  ...         0         0         0         0
3502       0       0       0       0  ...         0         0         0         0
4345       0       0       0       0  ...        76         0         0         0
5896       0       0       0       0  ...         0         0         0         0
3141       0       0       0       0  ...        49         0         0         0

[2000 rows x 784 columns]

In [163]:
X_r[0]

array([ -172.75832219, -1332.9556347 ])

In [164]:
# plt.style.use('fivethirtyeight')

# fig, axarr = plt.subplots(1, 2, figsize=(12, 4))

# sns.heatmap(pca.components_[0, :].reshape(28, 28), ax=axarr[0], cmap='gray_r')
# sns.heatmap(pca.components_[1, :].reshape(28, 28), ax=axarr[1], cmap='gray_r')
# axarr[0].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[0]*100),
#     fontsize=12
# )
# axarr[1].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[1]*100),
#     fontsize=12
# )
# axarr[0].set_aspect('equal')
# axarr[1].set_aspect('equal')

# plt.suptitle('2-Component PCA')

In [165]:
# pca = PCA(n_components=4)
# X_r = pca.fit(X).transform(X)

# plt.style.use('fivethirtyeight')

# fig, axarr = plt.subplots(2, 2, figsize=(12, 8))

# sns.heatmap(pca.components_[0, :].reshape(28, 28), ax=axarr[0][0], cmap='gray_r')
# sns.heatmap(pca.components_[1, :].reshape(28, 28), ax=axarr[0][1], cmap='gray_r')
# sns.heatmap(pca.components_[2, :].reshape(28, 28), ax=axarr[1][0], cmap='gray_r')
# sns.heatmap(pca.components_[3, :].reshape(28, 28), ax=axarr[1][1], cmap='gray_r')

# axarr[0][0].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[0]*100),
#     fontsize=12
# )
# axarr[0][1].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[1]*100),
#     fontsize=12
# )
# axarr[1][0].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[2]*100),
#     fontsize=12
# )
# axarr[1][1].set_title(
#     "{0:.2f}% Explained Variance".format(pca.explained_variance_ratio_[3]*100),
#     fontsize=12
# )
# axarr[0][0].set_aspect('equal')
# axarr[0][1].set_aspect('equal')
# axarr[1][0].set_aspect('equal')
# axarr[1][1].set_aspect('equal')

# plt.suptitle('4-Component PCA')
# pass

In [166]:
# X_r[0]

In [167]:
# pca = PCA(n_components=10)
# X_r = pca.fit(X).transform(X)

# plt.plot(range(10), pca.explained_variance_ratio_)
# plt.plot(range(10), np.cumsum(pca.explained_variance_ratio_))
# plt.title("Component-wise and Cumulative Explained Variance")
# pass

In [168]:
# trace0 = go.Scatter(
#     x = X_r[:,0],
#     y = X_r[:,1],
#     mode = 'markers',
#     text = y,
#     showlegend = False,
#     marker = dict(
#         size = 8,
#         color = y,
#         colorscale ='Jet',
#         showscale = False,
#         line = dict(
#             width = 2,
#             color = 'rgb(255, 255, 255)'
#         ),
#         opacity = 0.8
#     )
# )
# data = [trace0]

# layout = go.Layout(
#     title= 'Principal Component Analysis (PCA)',
#     hovermode= 'closest',
#     xaxis= dict(
#          title= 'First Principal Component',
#         ticklen= 5,
#         zeroline= False,
#         gridwidth= 2,
#     ),
#     yaxis=dict(
#         title= 'Second Principal Component',
#         ticklen= 5,
#         gridwidth= 2,
#     ),
#     showlegend= True
# )


# fig = dict(data=data, layout=layout)
# py.iplot(fig, filename='styled-scatter')

In [169]:
# plt.figure(figsize=(12,12))

# plt.scatter(X_r[y==0, 0], X_r[y==0, 1], color='red', alpha=0.5,label='0')
# plt.scatter(X_r[y==1, 0], X_r[y==1, 1], color='blue', alpha=0.5,label='1')
# plt.scatter(X_r[y==2, 0], X_r[y==2, 1], color='green', alpha=0.5,label='2')
# plt.scatter(X_r[y==3, 0], X_r[y==3, 1], color='black', alpha=0.5,label='3')
# plt.scatter(X_r[y==4, 0], X_r[y==4, 1], color='khaki', alpha=0.5,label='4')
# plt.scatter(X_r[y==5, 0], X_r[y==5, 1], color='yellow', alpha=0.5,label='5')
# plt.scatter(X_r[y==6, 0], X_r[y==6, 1], color='turquoise', alpha=0.5,label='6')
# plt.scatter(X_r[y==7, 0], X_r[y==7, 1], color='pink', alpha=0.5,label='7')
# plt.scatter(X_r[y==8, 0], X_r[y==8, 1], color='moccasin', alpha=0.5,label='8')
# plt.scatter(X_r[y==9, 0], X_r[y==9, 1], color='olive', alpha=0.5,label='9')
# plt.scatter(X_r[y==10, 0], X_r[y==10, 1], color='coral', alpha=0.5,label='10')
# plt.title("PCA")
# plt.ylabel('Les coordonnees de Y')
# plt.xlabel('Les coordonnees de X')
# plt.legend()
# plt.show()

In [170]:
# # Taking only the first N rows to speed things up
# X_PCA = X[:3000].values

# # Call the PCA method with 5 components. 
# pca = PCA(n_components=5)
# pca.fit(X_PCA)
# X_5d = pca.transform(X_PCA)

# # For cluster coloring in our Plotly plots, remember to also restrict the target values 
# Target_name = y[:3000].apply(true_label)
# Target = y[:3000]

## TSNE

In [171]:
tsne = TSNE(n_components=2, verbose=1, perplexity=40, n_iter=300)
tsne_results = tsne.fit_transform(X)

[t-SNE] Computing 121 nearest neighbors...
[t-SNE] Indexed 2000 samples in 0.133s...
[t-SNE] Computed neighbors for 2000 samples in 6.524s...
[t-SNE] Computed conditional probabilities for sample 1000 / 2000
[t-SNE] Computed conditional probabilities for sample 2000 / 2000
[t-SNE] Mean sigma: 499.685292
[t-SNE] KL divergence after 250 iterations with early exaggeration: 64.203506
[t-SNE] KL divergence after 300 iterations: 1.104165


In [172]:
tsne_results

array([[ -5.9099064 ,  -8.846801  ],
       [ -4.531579  , -12.044234  ],
       [ 13.879023  ,   3.286422  ],
       ...,
       [ 14.027925  ,   0.42236844],
       [-12.08762   , -12.016456  ],
       [ 14.634616  ,   1.8333458 ]], dtype=float32)

## MDS

In [173]:
mds = MDS(n_components=2, n_init=12, max_iter=400, metric=True, n_jobs=4, random_state=2019)
X_mds = mds.fit_transform(X)

In [174]:
X_mds

array([[  123.45606826,  1826.63913876],
       [-1203.84808741,  2089.58544775],
       [-2315.68996298, -2076.2162709 ],
       ...,
       [-1702.45803914, -1931.26088448],
       [ -455.34709   ,  2370.56102468],
       [-2760.4972236 , -1691.38657633]])

## Export data to json

In [175]:
lists_pca = X_r.tolist()
list_tsne = tsne_results.tolist()
list_mds = X_mds.tolist()
list_y = y["label"].values.tolist()
res = {"pca": lists_pca, "tsne": list_tsne, "mds": list_mds, "y": list_y}

In [176]:
with open('res.json', 'w') as fp:
    json.dump(res, fp)